
[package]

name = "tlpi_rust"
version = "0.0.1"
authors = [ "Charles Ruhland <cruhland@alumni.cmu.edu>" ]

[dependencies]

bitflags = "0.1.1"
getopts = "0.2.4"

[[bin]]

name = "copy"

[[bin]]

name = "seek_io"

[[bin]]

name = "tee"
